const myArray = ["ope", "eri", "wunmi", "chioma"]
console.log(myArray.join(" . "))
console.log(myArray.length)
console.log(myArray.reverse())
myArray.push("afa")
console.log(myArray)
myArray.pop()
console.log(myArray)
myArray.shift("afa")
console.log(myArray)