const myArray = ["ope", "eri", "wunmi", "chioma"]
console.log(myArray.join(" . "))
console.log(myArray.length)
console.log(myArray.reverse())
myArray.push("afa")
console.log(myArray)
myArray.pop()
console.log(myArray)
myArray.unshift("afa")
console.log(myArray)
myArray.shift()
console.log(myArray)
myArray.reverse()
console.log(myArray)
console.log(myArray.slice(1, 3))
console.log(myArray)
myArray.splice(1, 2, "elvis", "david")
console.log(myArray.toString())
console.log(myArray[myArray.length - 1])
console.log(myArray.at(-1))
const myarr2 = [[]]
myArray.forEach((val, index, arr)=>{
    console.log(val, index)
})
